In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

In [3]:
my_list=[1,2,3,4,5,6]
my_list

[1, 2, 3, 4, 5, 6]

In [4]:
type(my_list)

list

In [5]:
my_list

[1, 2, 3, 4, 5, 6]

In [6]:
arr1 = np.array(my_list)
arr1

array([1, 2, 3, 4, 5, 6])

In [7]:
type(arr1)

numpy.ndarray

#Arange

In [8]:
np.arange(10) #its indexing start from 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(12,25)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [11]:
np.arange(20,10) #1st argument less than 2nd argument

array([], dtype=int64)

In [12]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

#Zeros

In [13]:
np.zeros(5) #parameter tunning

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros(5,dtype=int) #hyperparameter tunning

array([0, 0, 0, 0, 0])

In [16]:
np.zeros([2,2],dtype=int) #(Row,Coloumn)

array([[0, 0],
       [0, 0]])

In [17]:
np.zeros([5,4]) # 5R, 4C

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros((10,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#np ones

In [19]:
np.ones(2)

array([1., 1.])

In [20]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [21]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [22]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#Random (rand)

In [23]:
arr1

array([1, 2, 3, 4, 5, 6])

In [24]:
rand(3,2)

NameError: name 'rand' is not defined

In [25]:
random.rand(3,2)

NameError: name 'random' is not defined

In [29]:
np.random.rand(3,2)

array([[0.78694407, 0.58824122],
       [0.41013641, 0.53894571],
       [0.33181719, 0.8944317 ]])

In [32]:
np.random.rand(5)

array([0.83899331, 0.7029478 , 0.82257241, 0.66266534, 0.05984147])

In [38]:
np.random.randint(3)

1

In [42]:
np.random.randint(0,10)

3

In [43]:
np.random.randint(5,50,5)

array([11, 17, 22, 10, 42])

In [44]:
np.random.randint(0,10,4)

array([3, 8, 9, 0])

In [46]:
n = np.random.randint(10,40,(8,10)) # 8R 10C and numbers between 10 to 40

In [48]:
n

array([[11, 28, 15, 23, 17, 14, 27, 26, 12, 19],
       [28, 25, 29, 14, 22, 23, 10, 31, 32, 38],
       [24, 29, 21, 18, 13, 31, 25, 20, 28, 10],
       [36, 30, 30, 12, 28, 37, 28, 36, 30, 10],
       [24, 35, 33, 18, 24, 16, 18, 18, 13, 34],
       [36, 27, 21, 15, 11, 12, 15, 18, 26, 33],
       [39, 18, 21, 20, 12, 16, 12, 38, 10, 12],
       [24, 35, 34, 32, 32, 32, 37, 10, 34, 34]])

In [49]:
n[5]

array([36, 27, 21, 15, 11, 12, 15, 18, 26, 33])

In [112]:
n[0:6]

array([[35, 30, 30, 36, 36, 35, 35, 38],
       [33, 33, 34, 37, 34, 36, 38, 33],
       [37, 31, 37, 32, 34, 31, 31, 31],
       [34, 35, 34, 38, 32, 31, 39, 36],
       [32, 38, 38, 35, 37, 30, 35, 37],
       [36, 34, 33, 39, 30, 39, 30, 33]])

In [52]:
n

array([[11, 28, 15, 23, 17, 14, 27, 26, 12, 19],
       [28, 25, 29, 14, 22, 23, 10, 31, 32, 38],
       [24, 29, 21, 18, 13, 31, 25, 20, 28, 10],
       [36, 30, 30, 12, 28, 37, 28, 36, 30, 10],
       [24, 35, 33, 18, 24, 16, 18, 18, 13, 34],
       [36, 27, 21, 15, 11, 12, 15, 18, 26, 33],
       [39, 18, 21, 20, 12, 16, 12, 38, 10, 12],
       [24, 35, 34, 32, 32, 32, 37, 10, 34, 34]])

In [53]:
n[::-1]

array([[24, 35, 34, 32, 32, 32, 37, 10, 34, 34],
       [39, 18, 21, 20, 12, 16, 12, 38, 10, 12],
       [36, 27, 21, 15, 11, 12, 15, 18, 26, 33],
       [24, 35, 33, 18, 24, 16, 18, 18, 13, 34],
       [36, 30, 30, 12, 28, 37, 28, 36, 30, 10],
       [24, 29, 21, 18, 13, 31, 25, 20, 28, 10],
       [28, 25, 29, 14, 22, 23, 10, 31, 32, 38],
       [11, 28, 15, 23, 17, 14, 27, 26, 12, 19]])

In [54]:
n

array([[11, 28, 15, 23, 17, 14, 27, 26, 12, 19],
       [28, 25, 29, 14, 22, 23, 10, 31, 32, 38],
       [24, 29, 21, 18, 13, 31, 25, 20, 28, 10],
       [36, 30, 30, 12, 28, 37, 28, 36, 30, 10],
       [24, 35, 33, 18, 24, 16, 18, 18, 13, 34],
       [36, 27, 21, 15, 11, 12, 15, 18, 26, 33],
       [39, 18, 21, 20, 12, 16, 12, 38, 10, 12],
       [24, 35, 34, 32, 32, 32, 37, 10, 34, 34]])

In [55]:
n[::2] #11 24 24 39

array([[11, 28, 15, 23, 17, 14, 27, 26, 12, 19],
       [24, 29, 21, 18, 13, 31, 25, 20, 28, 10],
       [24, 35, 33, 18, 24, 16, 18, 18, 13, 34],
       [39, 18, 21, 20, 12, 16, 12, 38, 10, 12]])

In [56]:
n

array([[11, 28, 15, 23, 17, 14, 27, 26, 12, 19],
       [28, 25, 29, 14, 22, 23, 10, 31, 32, 38],
       [24, 29, 21, 18, 13, 31, 25, 20, 28, 10],
       [36, 30, 30, 12, 28, 37, 28, 36, 30, 10],
       [24, 35, 33, 18, 24, 16, 18, 18, 13, 34],
       [36, 27, 21, 15, 11, 12, 15, 18, 26, 33],
       [39, 18, 21, 20, 12, 16, 12, 38, 10, 12],
       [24, 35, 34, 32, 32, 32, 37, 10, 34, 34]])

In [57]:
n[::3] # 11 36 39

array([[11, 28, 15, 23, 17, 14, 27, 26, 12, 19],
       [36, 30, 30, 12, 28, 37, 28, 36, 30, 10],
       [39, 18, 21, 20, 12, 16, 12, 38, 10, 12]])

In [58]:
n

array([[11, 28, 15, 23, 17, 14, 27, 26, 12, 19],
       [28, 25, 29, 14, 22, 23, 10, 31, 32, 38],
       [24, 29, 21, 18, 13, 31, 25, 20, 28, 10],
       [36, 30, 30, 12, 28, 37, 28, 36, 30, 10],
       [24, 35, 33, 18, 24, 16, 18, 18, 13, 34],
       [36, 27, 21, 15, 11, 12, 15, 18, 26, 33],
       [39, 18, 21, 20, 12, 16, 12, 38, 10, 12],
       [24, 35, 34, 32, 32, 32, 37, 10, 34, 34]])

In [59]:
n[::4] #11 24

array([[11, 28, 15, 23, 17, 14, 27, 26, 12, 19],
       [24, 35, 33, 18, 24, 16, 18, 18, 13, 34]])

In [60]:
n

array([[11, 28, 15, 23, 17, 14, 27, 26, 12, 19],
       [28, 25, 29, 14, 22, 23, 10, 31, 32, 38],
       [24, 29, 21, 18, 13, 31, 25, 20, 28, 10],
       [36, 30, 30, 12, 28, 37, 28, 36, 30, 10],
       [24, 35, 33, 18, 24, 16, 18, 18, 13, 34],
       [36, 27, 21, 15, 11, 12, 15, 18, 26, 33],
       [39, 18, 21, 20, 12, 16, 12, 38, 10, 12],
       [24, 35, 34, 32, 32, 32, 37, 10, 34, 34]])

In [61]:
n[::5] # 11 36

array([[11, 28, 15, 23, 17, 14, 27, 26, 12, 19],
       [36, 27, 21, 15, 11, 12, 15, 18, 26, 33]])

In [62]:
n

array([[11, 28, 15, 23, 17, 14, 27, 26, 12, 19],
       [28, 25, 29, 14, 22, 23, 10, 31, 32, 38],
       [24, 29, 21, 18, 13, 31, 25, 20, 28, 10],
       [36, 30, 30, 12, 28, 37, 28, 36, 30, 10],
       [24, 35, 33, 18, 24, 16, 18, 18, 13, 34],
       [36, 27, 21, 15, 11, 12, 15, 18, 26, 33],
       [39, 18, 21, 20, 12, 16, 12, 38, 10, 12],
       [24, 35, 34, 32, 32, 32, 37, 10, 34, 34]])

In [63]:
n[::2] # 11 24 24 39

array([[11, 28, 15, 23, 17, 14, 27, 26, 12, 19],
       [24, 29, 21, 18, 13, 31, 25, 20, 28, 10],
       [24, 35, 33, 18, 24, 16, 18, 18, 13, 34],
       [39, 18, 21, 20, 12, 16, 12, 38, 10, 12]])

In [64]:
n[0]

array([11, 28, 15, 23, 17, 14, 27, 26, 12, 19])

In [65]:
n[0:5]

array([[11, 28, 15, 23, 17, 14, 27, 26, 12, 19],
       [28, 25, 29, 14, 22, 23, 10, 31, 32, 38],
       [24, 29, 21, 18, 13, 31, 25, 20, 28, 10],
       [36, 30, 30, 12, 28, 37, 28, 36, 30, 10],
       [24, 35, 33, 18, 24, 16, 18, 18, 13, 34]])

In [67]:
nn=n[0,5]

In [81]:
np.random.randint(3,20,(1,9))

array([[ 4,  5,  3,  3,  6,  4,  6,  6, 15]])

In [73]:
np.random.rand(3,2)

array([[0.61744858, 0.18993546],
       [0.94997334, 0.76233434],
       [0.25901505, 0.05245157]])

In [82]:
np.random.randint(0,10,4)

array([6, 9, 5, 3])

In [83]:
np.random.randint(5,10,2)

array([8, 6])

In [89]:
n1 = np.random.randint(10,40,(10,8))

In [92]:
n1

array([[24, 39, 33, 20, 27, 21, 28, 13],
       [22, 38, 38, 36, 16, 26, 29, 22],
       [10, 23, 28, 20, 12, 11, 33, 12],
       [19, 24, 29, 12, 10, 27, 32, 18],
       [19, 15, 16, 23, 13, 22, 28, 37],
       [34, 11, 39, 20, 31, 21, 36, 25],
       [19, 34, 20, 20, 33, 37, 17, 18],
       [38, 19, 15, 17, 16, 15, 13, 13],
       [34, 33, 37, 23, 25, 19, 28, 29],
       [33, 37, 29, 24, 23, 26, 39, 25]])

In [101]:
print(int(n1[0,5])) #0th row 5th coloumn

21


In [102]:
int(n1[5,-3])


21

In [107]:
n = np.random.randint(30,40,(10,8))

In [108]:
n

array([[35, 30, 30, 36, 36, 35, 35, 38],
       [33, 33, 34, 37, 34, 36, 38, 33],
       [37, 31, 37, 32, 34, 31, 31, 31],
       [34, 35, 34, 38, 32, 31, 39, 36],
       [32, 38, 38, 35, 37, 30, 35, 37],
       [36, 34, 33, 39, 30, 39, 30, 33],
       [30, 32, 33, 33, 37, 32, 39, 39],
       [33, 37, 39, 35, 34, 39, 35, 39],
       [32, 36, 35, 30, 39, 39, 37, 34],
       [35, 31, 32, 31, 39, 33, 38, 34]])

In [109]:
int(n[5,3]) #Specific positions

30

In [116]:
n[5:] #called record only

array([[36, 34, 33, 39, 30, 39, 30, 33],
       [30, 32, 33, 33, 37, 32, 39, 39],
       [33, 37, 39, 35, 34, 39, 35, 39],
       [32, 36, 35, 30, 39, 39, 37, 34],
       [35, 31, 32, 31, 39, 33, 38, 34]])

#Arange Reshape

In [128]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [133]:
np.arange(2,8).reshape(3,2)

array([[2, 3],
       [4, 5],
       [6, 7]])

In [149]:
np.arange(0,12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])