In [2]:
import numpy as np

In [3]:
mat = np.arange(10)

In [4]:
mat

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
mat1 = np.arange(0,100).reshape(10,10)

In [9]:
mat1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [10]:
row = 4
col = 5

In [11]:
col

5

In [12]:
row

4

In [13]:
print(mat1[row,col])

45


In [14]:
row = 6
col = 3

In [16]:
print(mat1[row,col])

63


In [17]:
row = 7
col = 5

In [18]:
print(mat1[row,col])

75


In [19]:
row = 6
col = 9

In [20]:
print(mat1[row,col])

69


In [22]:
mat1[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
row = 7
col = 6
print(mat1[row,col])

76


In [30]:
mat1[7]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [31]:
#Using Slices
col = 5
print(mat1[:,col])  #how to print coloumn

[ 5 15 25 35 45 55 65 75 85 95]


In [33]:
mat1[col]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [34]:
mat1[:,4]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [35]:
mat1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [46]:
mat1[-1][::-1] #last index-reverse order

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90])

In [47]:
mat1[row,:]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [48]:
mat1[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [49]:
mat1[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [50]:
mat1[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [51]:
mat1[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
row = 4
mat1[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [57]:
col = 5
mat1[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [58]:
mat1[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
mat1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [60]:
mat1[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [62]:
mat1 < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [64]:
mat1[mat1<50] #Masking/Filter

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [65]:
mat1[mat1<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [66]:
mat1[mat1 == 50]

array([50])

In [67]:
mat1[mat1 != 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [69]:
mat1[mat1 > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Topic

In [73]:
#Create array from list
a = np.array([1,2,3])
print("Array:",a)

Array: [1 2 3]


In [71]:
type(a)

numpy.ndarray

In [74]:
#Create an array with linearly spaced values
c = np.linspace(0,1,5) #5steps b\w 0 to 1
print(c)

[0.   0.25 0.5  0.75 1.  ]


In [79]:
d = np.zeros((2,3)) #2r3c
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [80]:
d = np.ones((3,2))
print(d)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [81]:
f = np.eye(4) #4x4 identity matrix
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [83]:
#Array Manipulation Function
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(3,1)) #Reshape to 1x3
print(reshaped)

[[1]
 [2]
 [3]]


In [85]:
#flatten an array
f1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened = np.ravel(f1) #Flatten to 1d array
print(flattened)

[ 1  2  3  4  5  6  7  8  9 10]


In [88]:
#Transpose an array
e1 = np.array([[1,2],[3,4],[5,6],[7,8]])
transposed = np.transpose(e1)
print(transposed)

[[1 3 5 7]
 [2 4 6 8]]


In [90]:
#Stack arrays vertically
a2 = np.array([2,3])
b2 = np.array([4,5])
stacked = np.vstack([a2,b2])
stacked

array([[2, 3],
       [4, 5]])

In [92]:
#Mathematical Function
#Addtion of two array
g = np.array([1,2,3,4])
added = np.add(g,3)
added

array([4, 5, 6, 7])

In [93]:
#Square each element
squared = np.power(g,3)
squared

array([ 1,  8, 27, 64])

In [95]:
sqrt_val = np.sqrt(g)
print(sqrt_val) #Square root

[1.         1.41421356 1.73205081 2.        ]


In [96]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [98]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a) #Dot product of a and g
int(dot_product)

14

In [99]:
#Statistical Function
s = np.array([2,3,4,5])
mean = np.mean(s)
print(mean)

3.5


In [102]:
std_dev =np.std(s)
print("Standard deviation:",std_dev)

Standard deviation: 1.118033988749895


In [103]:
minimum = np.min(s)
print(minimum)

2


In [105]:
maximum = np.max(s)
print(maximum)

5


In [107]:
#Linear Algebra Function
matrix = np.array([[1,2],[3,4]])
print(matrix)

[[1 2]
 [3 4]]


In [108]:
determinant = np.linalg.det(matrix)
print(determinant)

-2.0000000000000004


In [109]:
inverse = np.linalg.inv(matrix)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [113]:
#Random Sampling Function
random_vals = np.random.rand(3)
print(random_vals)

[0.84030452 0.78315899 0.5930969 ]


In [123]:
np.random.seed(0)
#Generate random values between 0 to 1
random_vals=np.random.rand(3)
print("Randoms:",random_vals)

Randoms: [0.5488135  0.71518937 0.60276338]


In [124]:
rand_ints = np.random.randint(0,20,size = 5)
print(rand_ints)

[ 3  7  9 19 18]


In [125]:
np.random.seed(0)
#Generate random integers
rand_ints = np.random.randint(0,20,size = 5)
rand_ints

array([12, 15,  0,  3,  3])

In [127]:
#Boolean and Logical Functions
logical_test = np.array([True,False,True])
all_true = np.all(logical_test)
print(all_true)

False


In [128]:
logical_test=np.array([False,False,False])
all_true = np.all(logical_test)
print(all_true)

False


In [129]:
any_true = np.any(logical_test)
print(any_true)

False


In [130]:
#Set Operations
set_a = np.array([2,3,4,5])
set_b = np.array([4,5,7,8])
intertsec = np.intersect1d(set_a,set_b)
print(intertsec)

[4 5]


In [131]:
union = np.union1d(set_a,set_b)
print(union)

[2 3 4 5 7 8]


In [135]:
#array Attribute Functions
a = np.array ([3,4,5])
shape = a.shape #shape of array
size = a.size #size of array
dimensions = a.ndim #no of dimensions
dtype = a.dtype #data type of array
print(shape)
print(size)
print(dimensions)
print(dtype)

(3,)
3
1
int64


In [137]:
#Other Function
a = np.array([3,4,5])
copied_array = np.copy(a)
print(copied_array)

[3 4 5]


In [138]:
#Size in bytes of an array
array_size_in_bytes = a.nbytes
print(array_size_in_bytes)

24


In [139]:
shared = np.shares_memory(a,copied_array) #Check does a and copies array shared memory
print(shared)

False
